from dataclasses import dataclass

# 출력 토글
STRICT_FAKE_FILTER = True
SHOW_KKI_ONLY_WHEN_CONFIDENT = True
KKI_SHOW_MIN = 45
KKI_MEDIUM = 45
KKI_HIGH = 70

# 끼 프로파일 보조 기준
KKI_VOL_GOOD = 1.3
KKI_VOL_STRONG = 2.0
KKI_OBV_GOOD = 1
KKI_ATTACK_GOOD = 3
KKI_BLUE_GOOD = 3

# 밴드/엔벨로프 설명용 기준
BB_SQUEEZE_STRONG = 0.08
BB_SQUEEZE_MID = 0.14
ENV_TOUCH_NEAR = 0.02
